run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - bodyclose
    - contextcheck
    - gofmt
    - errcheck
    - errorlint
    - gocritic
    - godot
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - nilerr
    - tparallel
    - unparam
    - whitespace
    - bidichk
    - exportloopref
    - goconst
    - reassign
    - goimports
    - exhaustive
    - gci
    - gomodguard
    - prealloc
    - forbidigo
    - dogsled
    - nakedret
    - stylecheck
    - unconvert  
    - gocyclo
    - gosec
    - nolintlint
    - forcetypeassert
    - gochecknoglobals
    - asciicheck
    - goprintffuncname
    - nestif
    - noctx
